INSERT INTO 
    ingredient (amount, unit, "name", "recipeId")
VALUES
    (4, 'halves', 'boneless chicken breast', '1'),
    (2, 'tablespoons', 'butter ', '1'),
    (2, 'cans', 'condensed cream of chicken soup', '1'),
    (1, 'unit', 'onion finely diced', '1'),
    (2, 'packages', 'refrigerated biscuit dough, torn into pieces', '1'),
    (2, 'cans', 'condensed cream of mushroom soup', '2'),
    (1, 'package', 'dry onion soup mix', '2'),
    (0.25, 'cups', 'water', '2'),
    (5, 'pounds', 'pot roast', '2'),
    (0.5,'cup','packed brown sugar', '3'),
    (0.5, 'cup', 'ketchup', '3'),
    (1.5, 'pounds', 'lean ground beef', '3'),
    (0.75, 'cup', 'milk', '3'),
    (2, 'units', 'eggs', '3'),
    (4, 'halves', 'boneless chicken breast', '4'),
    (2, 'tablespoons', 'butter ', '4'),
    (2, 'cans', 'condensed cream of chicken soup', '4'),
    (1, 'unit', 'onion finely diced', '4'),
    (2, 'packages', 'refrigerated biscuit dough, torn into pieces', '4'),
    (2, 'cans', 'condensed cream of mushroom soup', '5'),
    (1, 'package', 'dry onion soup mix', '5'),
    (0.25, 'cups', 'water', '5'),
    (5, 'pounds', 'pot roast', '5'),
    (0.5,'cup','packed brown sugar', '6'),
    (0.5, 'cup', 'ketchup', '6'),
    (1.5, 'pounds', 'lean ground beef', '6'),
    (0.75, 'cup', 'milk', '6'),
    (2, 'units', 'eggs', '6'),
    (4, 'halves', 'boneless chicken breast', '7'),
    (2, 'tablespoons', 'butter ', '7'),
    (2, 'cans', 'condensed cream of chicken soup', '7'),
    (1, 'unit', 'onion finely diced', '7'),
    (2, 'packages', 'refrigerated biscuit dough, torn into pieces', '7'),
    (2, 'cans', 'condensed cream of mushroom soup', '8'),
    (1, 'package', 'dry onion soup mix', '8'),
    (0.25, 'cups', 'water', '8'),
    (5, 'pounds', 'pot roast', '8'),
    (0.5,'cup','packed brown sugar', '9'),
    (0.5, 'cup', 'ketchup', '9'),
    (1.5, 'pounds', 'lean ground beef', '9'),
    (0.75, 'cup', 'milk', '9'),
    (2, 'units', 'eggs', '9'),
    (4, 'halves', 'boneless chicken breast', '10'),
    (2, 'tablespoons', 'butter ', '10'),
    (2, 'cans', 'condensed cream of chicken soup', '10'),
    (1, 'unit', 'onion finely diced', '10'),
    (2, 'packages', 'refrigerated biscuit dough, torn into pieces', '10'),
    (2, 'cans', 'condensed cream of mushroom soup', '11'),
    (1, 'package', 'dry onion soup mix', '11'),
    (0.25, 'cups', 'water', '11'),
    (5, 'pounds', 'pot roast', '11'),
    (0.5,'cup','packed brown sugar', '12'),
    (0.5, 'cup', 'ketchup', '12'),
    (1.5, 'pounds', 'lean ground beef', '12'),
    (0.75, 'cup', 'milk', '12'),
    (2, 'units', 'eggs', '12'),
    (4, 'halves', 'boneless chicken breast', '13'),
    (2, 'tablespoons', 'butter ', '13'),
    (2, 'cans', 'condensed cream of chicken soup', '13'),
    (1, 'unit', 'onion finely diced', '13'),
    (2, 'packages', 'refrigerated biscuit dough, torn into pieces', '13'),
    (2, 'cans', 'condensed cream of mushroom soup', '14'),
    (1, 'package', 'dry onion soup mix', '14'),
    (0.25, 'cups', 'water', '14'),
    (5, 'pounds', 'pot roast', '14'),
    (0.5,'cup','packed brown sugar', '15'),
    (0.5, 'cup', 'ketchup', '15'),
    (1.5, 'pounds', 'lean ground beef', '15'),
    (0.75, 'cup', 'milk', '15'),
    (2, 'units', 'eggs', '15');